version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # RabbitMQ Management UI
      - "5672:5672"   # RabbitMQ server port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  consul:
    image: hashicorp/consul:1.19.2
    container_name: consul
    ports:
      - "8500:8500/udp"
      - "8500:8500"   # Consul HTTP API
    command: 'agent -dev -node=micro_smth -client=0.0.0.0 -log-level=INFO'
